### ISSUE TITLE
Connect Ionic App to Hasura Graphql

### ISSUE THREAD

**Issue by mdwagner** [mdwagner/next-great-idea#1]
Check out this article:

https://www.apollographql.com/docs/react/data/queries/

https://www.apollographql.com/docs/react/get-started/

**Comment by wtmerchant3** [comment]
Continue next week from get started article with "Request Data"

**Comment by wtmerchant3** [comment]
I think I'm done with this ticket, next thing I will focus on is creating a sign up page for new users. I'll continue using this tutorial to learn how to persist data to the database from the UI: 

https://www.apollographql.com/docs/react/data/queries/
